# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Builds the DirectXTK Starter Kit

schedules:
- cron: "0 1 * * *"
  displayName: 'Nightly build'
  branches:
    include:
    - main

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  GUID_FEED: $(ADOFeedGUID)

pool:
  vmImage: windows-2019

jobs:
- job: BUILD_KIT
  displayName: 'Builds using VS'
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet'
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: DirectXTKStarterKit.sln
      feedRestore: $(GUID_FEED)
      includeNuGetOrg: false
  - task: VSBuild@1
    displayName: Build solution Debug/x64
    inputs:
      solution: DirectXTKStarterKit.sln
      vsVersion: 16.0
      platform: x64
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution Release/x64
    inputs:
      solution: DirectXTKStarterKit.sln
      vsVersion: 16.0
      platform: x64
      configuration: Release
  - task: VSBuild@1
    displayName: Build solution Debug/x86
    inputs:
      solution: DirectXTKStarterKit.sln
      vsVersion: 16.0
      platform: x86
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution Release/x86
    inputs:
      solution: DirectXTKStarterKit.sln
      vsVersion: 16.0
      platform: x86
      configuration: Release
  - task: VSBuild@1
    displayName: Build solution Debug/ARM64
    inputs:
      solution: DirectXTKStarterKit.sln
      vsVersion: 16.0
      platform: ARM64
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution Release/ARM64
    inputs:
      solution: DirectXTKStarterKit.sln
      vsVersion: 16.0
      platform: ARM64
      configuration: Release
