# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Microsoft C++ Code Analysis

on:
  push:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
  pull_request:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
  schedule:
    - cron: '25 15 * * 5'

permissions:
  contents: read

# Can't use microsoft/msvc-code-analysis-action as it fails on the ../Framework/Source.cpp files

jobs:
  analyze_dx11:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: amd64

      - name: Configure CMake
        working-directory: ${{ github.workspace }}/DX11
        run: cmake --preset=x64-Debug -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON -DENABLE_CODE_ANALYSIS=ON

      - name: Build CMake
        working-directory: ${{ github.workspace }}/DX11
        run: cmake --build out/build/x64-Debug --config Debug

  analyze_dx12:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: amd64

      - name: Configure CMake
        working-directory: ${{ github.workspace }}/DX12
        run: cmake --preset=x64-Debug -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON -DENABLE_CODE_ANALYSIS=ON

      - name: Build CMake
        working-directory: ${{ github.workspace }}/DX12
        run: cmake --build out/build/x64-Debug --config Debug
